// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPAri-MIoJRL3lUvfp61TzyKqiQFSW6KY',
    appId: '1:1091000729274:web:107592474b9978b5588c83',
    messagingSenderId: '1091000729274',
    projectId: 'true-hadith-e3f19',
    authDomain: 'true-hadith-e3f19.firebaseapp.com',
    storageBucket: 'true-hadith-e3f19.firebasestorage.app',
    measurementId: 'G-VN00400DBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlum1bmXkWoqVD_jn9B-ep6n2utb2pWAs',
    appId: '1:1091000729274:android:57874a589b173e6b588c83',
    messagingSenderId: '1091000729274',
    projectId: 'true-hadith-e3f19',
    storageBucket: 'true-hadith-e3f19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDrcNzv48EkW0Wcf9kDr-g4hf2Zk6C6EI',
    appId: '1:1091000729274:ios:55ca98de2bb0f427588c83',
    messagingSenderId: '1091000729274',
    projectId: 'true-hadith-e3f19',
    storageBucket: 'true-hadith-e3f19.firebasestorage.app',
    iosBundleId: 'com.example.trueHadith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDrcNzv48EkW0Wcf9kDr-g4hf2Zk6C6EI',
    appId: '1:1091000729274:ios:55ca98de2bb0f427588c83',
    messagingSenderId: '1091000729274',
    projectId: 'true-hadith-e3f19',
    storageBucket: 'true-hadith-e3f19.firebasestorage.app',
    iosBundleId: 'com.example.trueHadith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPAri-MIoJRL3lUvfp61TzyKqiQFSW6KY',
    appId: '1:1091000729274:web:9f975fea2a8862f6588c83',
    messagingSenderId: '1091000729274',
    projectId: 'true-hadith-e3f19',
    authDomain: 'true-hadith-e3f19.firebaseapp.com',
    storageBucket: 'true-hadith-e3f19.firebasestorage.app',
    measurementId: 'G-E1LWQVSVP3',
  );

}